### ISSUE TITLE
MersenneTwister and c++17

### ISSUE THREAD

**Issue by algebravic** [meelgroup/cmsgen#4]
I tried `pip install pycmsgen`, on an arm2 Apple, I got a bunch of errors like the following:

```
  src/MersenneTwister.h:187:2: error: ISO C++17 does not allow 'register' storage class specifier [-Wregister]
          register uint32 s1;
          ^~~~~~~~~

```

**Comment by msoos** [comment]
Aaaa that’s interesting! Thanks for that. Okay, I think I can fix that
tomorrow. Let me try and maybe tomorrow you can try again? I’ll write here
when I have a fix :) Thanks again,

Mate

**Comment by algebravic** [comment]
Thanks, Mate!

**Comment by msoos** [comment]
Hi,

This should fix it: b883c333f82cc71f06d9448760a7460b76ea418d I have kicked off a new pypi release that should finish in about 10-15m. That should (may?) work :) Let me know how it goes. If you get any errors, please do let me know. I'll try to fix them  :)

Mate

**Comment by msoos** [comment]
Hahah crap, I forgot to fix this, I fixed it in CryptoMiniSat etc. but not here :D Sorry, let me try!

**Comment by msoos** [comment]
Ok, now I have it pushed to PyPi and I have tested it with Windows & Mac but both are x86. I have removed MersenneTwister, so I think that should fix it... but I am not 100% sure. Please let me know!

Mate

**Comment by algebravic** [comment]
Hi Mate, That worked!  One minor point, in the docstring for Solver, you say that solve returns a tuple of status,  model. That doesn't seem to be the case, as one needs to call get_model for now,  The docstring should be fixed to reflect this.  Also, it should be made clearer that calling solve, produces another pseudo uniform sample.  At least that's what I think.

**Comment by msoos** [comment]
Ah, good points! I have now pushed 6.0.5, which fixes the `solve()` to return what the description says :) So this changes the API a little but, but brings it in line with `pycryptosat`. I hope this helps!

Thanks again for everything,

Mate

**Comment by algebravic** [comment]
Mate, You're welcome!
